-- ============================================================
-- Escape — Supabase Schema
-- Run this in your Supabase SQL Editor (Dashboard → SQL Editor)
-- ============================================================

-- Enable UUID generation
create extension if not exists "pgcrypto";


-- ── users ──────────────────────────────────────────────────
-- Minimal user record. In production, hook this to Supabase Auth
-- via a trigger on auth.users so rows are created automatically.

create table if not exists public.users (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now()
);

comment on table public.users is
  'One row per Escape user. Extend with email/display_name when you add Auth.';


-- ── sessions ───────────────────────────────────────────────
-- One row per task-breaking session. steps_json holds the full
-- blueprint array so we never need a separate steps table for
-- basic history queries.

create table if not exists public.sessions (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.users(id) on delete cascade,
  goal          text not null,
  steps_json    jsonb not null default '[]',   -- full micro_steps array
  energy_level  smallint check (energy_level between 1 and 10),
  low_power_mode boolean not null default false,
  five_second_start text,
  stuck_count   smallint not null default 0,   -- how many times user got stuck
  created_at    timestamptz not null default now(),
  completed_at  timestamptz                    -- null = in-progress
);

create index if not exists sessions_user_id_idx
  on public.sessions(user_id);

create index if not exists sessions_completed_at_idx
  on public.sessions(user_id, completed_at)
  where completed_at is not null;

comment on column public.sessions.steps_json is
  'Full micro_steps array as generated by Claude. Stored as JSONB for cheap reads.';

comment on column public.sessions.completed_at is
  'Set when all steps are marked done. NULL means session is still active.';


-- ── streaks ────────────────────────────────────────────────
-- One row per user. Upserted (never inserted twice) by the
-- recalculate_streak() function whenever a session completes.

create table if not exists public.streaks (
  user_id         uuid primary key references public.users(id) on delete cascade,
  current_streak  int not null default 0,
  longest_streak  int not null default 0,
  last_completed  date,   -- calendar date of last completed session (UTC)
  updated_at      timestamptz not null default now()
);

comment on table public.streaks is
  'Streak counters per user. Recalculated on every session completion.';


-- ── Row Level Security ─────────────────────────────────────
-- These policies assume you will eventually add Supabase Auth.
-- For now they allow all operations (service-role key bypasses RLS anyway).
-- Uncomment and tighten when you wire up auth.users.

alter table public.users    enable row level security;
alter table public.sessions enable row level security;
alter table public.streaks  enable row level security;

-- Permissive policies for service-role access (your FastAPI backend)
create policy "service role full access on users"
  on public.users for all using (true);

create policy "service role full access on sessions"
  on public.sessions for all using (true);

create policy "service role full access on streaks"
  on public.streaks for all using (true);


-- ── recalculate_streak() ───────────────────────────────────
-- Pure SQL streak engine. Call this (via the FastAPI layer) whenever
-- a session is marked complete. It:
--   1. Fetches the ordered list of completion dates for the user.
--   2. Walks the dates to compute current + longest streak.
--   3. Upserts the streaks row.
--
-- A "day" is a UTC calendar date. Completing multiple sessions in one
-- day counts as 1 streak day. A streak breaks when there is a gap of
-- more than 1 calendar day between consecutive completion dates.

create or replace function public.recalculate_streak(p_user_id uuid)
returns table (
  current_streak  int,
  longest_streak  int,
  last_completed  date
)
language plpgsql
as $$
declare
  v_dates          date[];
  v_current        int := 0;
  v_longest        int := 0;
  v_running        int := 1;
  v_last_date      date;
  v_prev_date      date;
  i                int;
begin
  -- Collect distinct completion dates, ascending
  select array_agg(d order by d)
  into   v_dates
  from (
    select distinct completed_at::date as d
    from   public.sessions
    where  user_id      = p_user_id
      and  completed_at is not null
  ) sub;

  -- No completions yet
  if v_dates is null or array_length(v_dates, 1) = 0 then
    -- Ensure a zeroed streaks row exists
    insert into public.streaks (user_id, current_streak, longest_streak, last_completed, updated_at)
    values (p_user_id, 0, 0, null, now())
    on conflict (user_id) do update
      set current_streak = 0,
          updated_at     = now();

    return query select 0::int, 0::int, null::date;
    return;
  end if;

  v_last_date := v_dates[array_length(v_dates, 1)];
  v_longest   := 1;

  -- Walk dates to find longest streak
  for i in 2 .. array_length(v_dates, 1) loop
    v_prev_date := v_dates[i - 1];
    if v_dates[i] - v_prev_date = 1 then
      v_running := v_running + 1;
    else
      v_running := 1;
    end if;
    if v_running > v_longest then
      v_longest := v_running;
    end if;
  end loop;

  -- Current streak: walk backwards from today
  v_current := 0;
  declare
    v_today   date := current_date;
    v_check   date := v_last_date;
    v_idx     int  := array_length(v_dates, 1);
  begin
    -- Allow streak to still be "live" if last completion was yesterday or today
    if v_today - v_last_date > 1 then
      v_current := 0;   -- streak has broken
    else
      v_current := 1;
      v_idx := array_length(v_dates, 1) - 1;
      while v_idx >= 1 loop
        if v_dates[v_idx + 1] - v_dates[v_idx] = 1 then
          v_current := v_current + 1;
          v_idx := v_idx - 1;
        else
          exit;
        end if;
      end loop;
    end if;
  end;

  -- Upsert streaks row
  insert into public.streaks (user_id, current_streak, longest_streak, last_completed, updated_at)
  values (p_user_id, v_current, v_longest, v_last_date, now())
  on conflict (user_id) do update
    set current_streak = excluded.current_streak,
        longest_streak = greatest(public.streaks.longest_streak, excluded.longest_streak),
        last_completed = excluded.last_completed,
        updated_at     = now();

  return query select v_current, v_longest, v_last_date;
end;
$$;

comment on function public.recalculate_streak is
  'Recomputes current and longest streaks for a user from their completed sessions.
   Call after every session completion. Safe to call multiple times (idempotent).';
